# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded9319763147f96831f9dcd6839825ffed556d284f86462f681986610e1e958e725365fdf5ab074c4abd051ace1f5cd84e5b478609174097918cb39ac9d05c5

test:
  secret_key_base: 9409a043ef24ce9b4ee4d38e98dc29e6bfbe10ff10e02ef9cbcd7f0f0d84d232671d603d82def594d4075a6c51a66c3e6dc1d09444989bf49f13c44106f613cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
